# Site settings
name: Enrico's Blog
title: Enrico's Blog
email: enrico.pelizzon@gmail.com
description: "A simple blog with thoughts about software development" 
baseurl: ""
url: "http://theimplementer.github.io"

# Build settings
markdown: kramdown
permalinks: pretty
highlighter: pygments
